### ISSUE TITLE
Error to recognition

### ISSUE THREAD

**Issue by RitaSghe** [thebigpotatoe/node-red-contrib-face-recognition#22]
Hi,
I have this error by using your flow ...
---
"[face-api-input:453418e3.520f28] - Child - child_process exited with code 0 and signal null"

---

Can you help me?

**Comment by mbrunn** [comment]
+1
The given example outputs signal null
If I add my own images, the same "ENOENT" error appears.

**Comment by thebigpotatoe** [comment]
Happy to have a look at this issue. But since the example is still working for me, I will need you to describe the _exact_ steps that you took to do this. That way I can try replicate it here on my setup.

**Comment by jmorris644** [comment]
I am having the same issue.
```
"No descriptor file found for 0b73162f0f4ec079"
```
Here are the steps:

1. click on pencil to add new face-api...
2. Enter in name
3. Click add image button
4. add image
5. get message to click "update" to upload, There is no update button Just an "Add" button at the top.
6. Click Add, then Done, then Deploy. Error message appears.

**Comment by jmorris644** [comment]
More info from the node-red-log

When I add an image to a newdescripter I get
```
7 Jan 10:12:11 - [error] undefined
```
When I click on the "Add" button I get
```

(node:76447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:76447) UnhandledPromiseRejectionWarning: TypeError: engine_1.ENGINE.makeTensor is not a function
    at makeTensor (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/ops/tensor_ops.js:97:28)
    at Object.tensor (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/ops/tensor_ops.js:54:12)
    at _loop_2 (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:219:36)
    at Object.decodeWeights (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:223:9)
    at /home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:255:66
    at Array.forEach (<anonymous>)
    at /home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:253:44
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:237:45)
    at step (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:48:23)
(node:76447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:76447) UnhandledPromiseRejectionWarning: TypeError: engine_1.ENGINE.makeTensor is not a function
    at makeTensor (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/ops/tensor_ops.js:97:28)
    at Object.tensor (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/ops/tensor_ops.js:54:12)
    at _loop_2 (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:219:36)
    at Object.decodeWeights (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/io_utils.js:223:9)
    at /home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:255:66
    at Array.forEach (<anonymous>)
    at /home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:253:44
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:237:45)
    at step (/home/joe/.node-red/node_modules/tfjs-image-recognition-base/node_modules/@tensorflow/tfjs-core/dist/io/weights_loader.js:48:23)
(node:76447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:76234) UnhandledPromiseRejectionWarning: Child - child_process exited with code 0 and signal null
(node:76234) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

Unrelated but another strange this is that on the debug messages the node ID does not display. I have never seen that before.

**Comment by jmorris644** [comment]
I resolved the majority of the issues. Your instructions state to install
```
npm install @tensorflow/tfjs-node
``
I installed 
```
npm install @tensorflow/tfjs-node@1.2.11
```
And then removed and reinstalled face recognition.

All of the errors are gone except for the undefined error that I state above.

One note: I have yet to get a face recognition with my testing. I will report on that when I learn more.
